Bye MelFidList
It's capital sin was overriding pack_subrecord_data/load_data

MelFidList\(b?('[A-Z]{4}'),[ ]?u?('[A-Za-z_]+'),?\) ->
MelArray(u$2, MelFid(b$1))

fixup!     Bye MelFidList

@@ -873,3 +873,3 @@ class MelFid(MelUInt32):

-    def __init__(self, mel_sig, element=u''):
+    def __init__(self, mel_sig, element=u'FID_'):
         super(MelFid, self).__init__(mel_sig, element)

localize.py   87 setup_locale: Set wx locale to 'English' (en_US)
localize.py   95 setup_locale: Set Wrye Bash locale to 'English'
bash.py  230 dump_environment: Using Wrye Bash Version 308
bash.py  230 dump_environment: OS info: Windows-10-10.0.19041, running on Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
bash.py  230 dump_environment: Python version: 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
bash.py  230 dump_environment: wxPython version: 4.1.0 msw (phoenix) wxWidgets 3.1.4
bash.py  230 dump_environment: python-lz4 version: 2.2.1; bundled LZ4 version: 1.9.2
bash.py  230 dump_environment: pyyaml version: 5.3.1
bash.py  230 dump_environment: Input encoding: UTF-8; output encoding: None
bash.py  230 dump_environment: Filesystem encoding: mbcs
bash.py  230 dump_environment: Command line: ['C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw', '-d']
bash.py  230 dump_environment: Using scandir v1.10.0
fail bash\brec\common_records.py
fail bash\brec.py
fail bash\game.py
fail bash\bush.py
Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.

Traceback (most recent call last):
  File "bash\bash.py", line 321, in _main
    bashIni, bush_game, game_ini_path = _detect_game(opts, bash_ini_path)
  File "bash\bash.py", line 438, in _detect_game
    bush_game = _import_bush_and_set_game(opts, bashIni)
  File "bash\bash.py", line 454, in _import_bush_and_set_game
    from . import bush
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 62, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\bush.py", line 32, in <module>
    from . import game as game_init
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 75, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\game\__init__.py", line 33, in <module>
    from .. import brec
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 75, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\brec\__init__.py", line 32, in <module>
    from .common_records import *
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 62, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\brec\common_records.py", line 133, in <module>
    class MreFlst(MelRecord):
  File "bash\brec\common_records.py", line 139, in MreFlst
    MelGroups(u'formIDInList', MelFid(b'LNAM')),
  File "bash\brec\basic_elements.py", line 553, in __init__
    super(MelGroups, self).__init__(attr, *elements)
  File "bash\brec\basic_elements.py", line 470, in __init__
    class _MelObject(self.__class__._mel_object_base_type):
ImportError: caused by ImportError(u'caused by ImportError(u\'caused by ImportError(u"caused by TypeError(\\\'Error when calling the metaclass bases\\\\\\\\n    __slots__ must be identifiers\\\',)",)\',)',)